apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.name }}
    template: js-app-deploy-template
  name: {{ .Values.name }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
