apiVersion: v2
dependencies:
- name: app-helm-common
  repository: ""
  version: '>=1.0.0'
description: A template to deploy your an App with a HTTP endpoint
name: js-app-deploy
tags: http
type: application
version: v0.0.1
